### ISSUE TITLE
Chat not displaying

### ISSUE THREAD

**Issue by mikegresham** [receevi/receevi#11]
Hello,

I'm experiencing a bug, I have only just installed and deployed, so may have done something wrong during setup. When trying to open a chat, I am just presented with a blank screen. I can see this in the log:

"Error: Invalid revalidate value "[object Object]" on "/chats/447514960631", must be a non-negative number or "false"
at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:8324
at rz (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:8506)
at async /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:9489
at async Promise.all (index 0)
at async rz (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:9297)
at async /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:9489
at async Promise.all (index 0)
at async rz (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:9297)
at async /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:9489
at async Promise.all (index 0) {
digest: '2506185614'
}"

The log is attached.

[whatsapp-webhooks-liv-central-logs-1724152019936.txt](https://github.com/user-attachments/files/16674749/whatsapp-webhooks-liv-central-logs-1724152019936.txt)

**Comment by mikegresham** [comment]
Turns out it was errors during setup.

running 'supabase functions deploy' resulted in:

Error: failed to load 'file:///{...}/workspace/webhooks/receevi/supabase/functions/_shared/database.types.ts': Module not found "file:///{...}/workspace/webhooks/receevi/supabase/functions/_shared/database.types.ts"

when cloning the git repository, for some reason 'database.types.ts' was not a file, but just a shortcut to it. Once I'd copied the file in the folder, and removed the shortcut - it worked.
